### PR TITLE
THE HIGHWAYMEN

### PR DESCRIPTION
**Pull request by Hekzder**
## About The Pull Request

WIP PR to add in THE HIGHWAYMEN to (mostly) replace the Rangers on Drought. 

This still needs:

- [x] Final loot spawner placement for Highwaymen base and adjacent mining area
- [x] Tweaks to Desert Rangers to turn them into a very small aid force without a base (two Rangers, a Ranger sniper, a Doctor)
- [ ] Special ammo crafting for Highwaymen QM
- [ ] Actually making sure everything fully works as intended
- [x] Final tweaks as needed

## Why It's Good For The Game

yea

### CODE REVIEW

**Comment by Hekzder** [comment]
image
yea

**Comment by BadAtThisGame302** [comment]
Yeah no way this guy's removing the NCR Rangers, bad PR -1 from me.

**Comment by Technical-l** [comment]
> Yeah no way this guy's removing the NCR Rangers, bad PR -1 from me.

ranger from new california republic reporting in!

**Comment by Hekzder** [comment]
This is tentatively good for a merge/for the test but we should likely test again right before main test if possible. Haven't had as much time to test as I'd like and stuff like the QM ammo crafting likely won't be in for this. Otherwise it should be good and we can maybe just TM for the first day to be safe.

**Comment by ProfessorPopoff** [comment]
I've pushed a commit to this rebranding them to be more along what they were speculated to be a while ago. Here's hoping it's enough of a soul change to keep them from being tartered up in the head. Along with that, a couple lil map fixes.

Also, Road runner gets a 9mm instead. 10mm kinda crazy doe

**Pull request merged**
