### PR TITLE
The disinfectioning

### PR DESCRIPTION
**Pull request by 1glitchycent**
## About The Pull Request

Makes infections roughly 3 times slower

## Why It's Good For The Game
fuck that shit dawg

## Changelog

:cl:
add: change infestation to 0.025
/:cl:

### CODE REVIEW

**Comment by ProfessorPopoff** [comment]
How long does it take. Throw some numbers

**Comment by 1glitchycent** [comment]
> How long does it take. Throw some numbers

I need to test it. will do so tomorrow.

**Comment by Hekzder** [comment]
First MS13 salt PR

**Comment by ProfessorPopoff** [comment]
I wonder if he tested it

**Pull request merged**
