### PR TITLE
Adds a ghoul pit in the NCR base for executing raiders

### PR DESCRIPTION
**Pull request by bardinatavern4**
It's very HRP!!!!!

(please I want to throw Original into the ghoul pit please please please please please please please please please please please)

### CODE REVIEW

**Comment by TheRealScarHomie** [comment]
Hey there! Please on your first mapping PR could you upload images of the changes you have made to the area! Thank you! _This was an automated message from the mojave sun development team tm_

**Comment by mrpibb4201337** [comment]
is that right

**Comment by Hekzder** [comment]
**First-time contributors need a maintainer to approve running workflows.**

**Comment by bardinatavern4** [comment]
1984?
hold on it's still compiling

**Comment by TheRealScarHomie** [comment]
1984 (MCMLXXXIV) was a leap year starting on Sunday of the Gregorian calendar, the 1984th year of the Common Era (CE) and Anno Domini (AD) designations, the 984th year of the 2nd millennium, the 84th year of the 20th century, and the 5th year of the 1980s decade.

**Comment by ProfessorPopoff** [comment]
Unable to render map diffs- How do you even do that?

**Comment by bardinatavern4** [comment]
> Unable to render map diffs- How do you even do that?

im just too good

**Comment by mrpibb4201337** [comment]
lol what

**Comment by bardinatavern4** [comment]
> lol what

skill issue

**Comment by mrpibb4201337** [comment]
> > lol what
> 
> skill issue

yea it is... yours 😆 🤣 😄 🙂 😐 🙁

**Pull request closed without merging**
