### PR TITLE
Mammoth Healthcare: Hospital

### PR DESCRIPTION
**Pull request by EdwardNashton**
Remade a Clinic to a Hospital with a 33 floors.

"Below" level: spare generator, morgue, a couple of "isolation wards for a psychos"

below

"Ground" level: "paramedical and trauma" department  with surgery, garage,  a medicine warehouse, some offices, dressroom for doctors and a couple of wards.

ground

"Above" level:  "infection isolation wing" with couple of wards and laboratory, "isolation wing kitchen and laundry", doctor's cabinets, small cafeteria, toilets, conference room, "CMO's" cabinet.

above

### CODE REVIEW

**Comment by Sinbest** [comment]
I can't believe you just casually dropped the first 33 floor building in BYOND.

**Comment by Sinbest** [comment]
Also, images please

**Comment by Sinbest** [comment]
Why the green tiles? The blue ones weren't the best but they matched the doors and made more sense than green ones.

**Comment by EdwardNashton** [comment]
> 

Because I'm tired of god damn navy tiles, and we didn't used green ones yet.
If Infra will made something better - I'll change it. But for now it's green. Deal with it.

**Comment by Hekzder** [comment]
If you want to use green tiles just use them in one of the military bases for one of their clinics/medbays or something, it would make so much more sense and look better than a random civilian hospital full of green tile.

**Comment by EdwardNashton** [comment]
> If you want to use green tiles just use them in one of the military bases for one of their clinics/medbays or something, it would make so much more sense and look better than a random civilian hospital full of green tile.

image

**Comment by ProfessorPopoff** [comment]
A couple things need to change or get fixed before I can merge this, unfortunately.

image
image
image
image

This door format doesn't work, and it's currently impossible to get a good looking doubledoor on W/E facing ones, unfortunately. Leaving them here like this would be a sin.

Similarly, putting a door up directly against the windows like this is bad looking.
image
image
It may be better once we get new window frame sprites, but for now it looks awful.

image
Once the safes are working again (actually suck up stuff on round init) the drink on this table is going to just get shoved in it.

You're nearing danger zone with these TG assets. If you could cut those, it'd be great.
image
image

no comment (i lied, my comment is please replace this ahead of time to literally just the white tiles until we get the others made and in)
image
I like to give artistic liberty to people that make PRs but this is cursed and will end up getting replaced anyways before we test.

Like any other time. Thanks for your efforts. When this is addressed, I can merge it.

**Comment by ProfessorPopoff** [comment]
Good enough for now. Impending changes to floor choice... 

Thanks.

**Pull request merged**
