### PR TITLE
[Mammoth] Vault Overhaul

### PR DESCRIPTION
**Pull request by Keksk**
## About The Pull Request

Overhauls Vault [ Also edits the tiles used in the  enclave bunker beneath the vault too ]

## Screenshots

Bunker overhaul:

:cl:
add: Mammoth Vault overhaul
/:cl:

### CODE REVIEW

**Comment by Hyperstellarwithguns** [comment]
i am not a mapper.
but i think this looks based.

**Comment by ProfessorPopoff** [comment]
Looks nice. I'll comb over it when i've got a bit of time. Side note: This PR also touches this area. 
image

**Comment by Keksk** [comment]
> 
> 
> Looks nice. I'll comb over it when i've got a bit of time. Side note: This PR also touches this area.
> image

Woops 😳 Imma add that too in the description

**Comment by ProfessorPopoff** [comment]
Overall has a much better shape, In my opinion. Thanks again for taking the time to help us out again, Kekss. A couple misc comments I've got, with one or two issues that could be addressed. 

For the two issues- 
image
You could probably add two/three high tier random spawners, just remove the static stimpak spawns. Also, i'm sure you could use one of our own crate sprites for that container. We've got some more now, as you probably saw.

image
I've got a bit of an opinion on that we shouldn't overdo certain concepts. Easier said than done. Pipes look nice but it's probably better to limit them. For instance: In the brotherhood base I've got it solely on the bottom level and mostly in the generator/warehouse room. These are a bit all over the place. You also need to keep in mind these do actually **TRIP** people sometimes when walking over them. They're aimed to be a funny little thing that limits movements in some place without outright blocking you...
 But it's a bit excessive here. Make sure any rooms have a covered way to get in. The bunker clinic has no way to get in without stepping over pips!
 
image
Also, this book case in the town radio room is covering up the window. Kinda weird.

 Personal comments:
image
Strange choice to have railings there. I might even have a smaller desk.

image
Trim down the blocky bits like this. Expand that bathroom to be a 2x2 if you've got to.

image
This is a bit of an abrupt pit, no? Could make it a tiny bit bigger than that, so that it's not just an outright rock tube downwards

>Aesthetic choices

image
Completely personal opinion here, even moreso than the others. This room is a bit weird. The floor has a bit too much going on for it, personally. 

image
 And i'd shorten this desk a bit.

All in all- It looks good. Just fix up those few things that I request and i'll be able to merge it.

**Comment by ProfessorPopoff** [comment]
Everything seems relatively fine, and my requests were fixed. Thanks again, merging it now.

**Pull request merged**
