### PR TITLE
The Jobbening

### PR DESCRIPTION
**Pull request by Hekzder**
## About The Pull Request

This PR will basically finalize all job loadouts for Mammoth so we can get them ready in preparation for CBT in the next month or so. 

## Why It's Good For The Game

Jobs are important. Mammoth currently has an employment crisis.

### CODE REVIEW

**Comment by Hekzder** [comment]
For now this just has the Wastelander job. Others will come later as needed, also includes some tweaks and new clothing items as needed once I found some issues while looking through them.

**Comment by Hekzder** [comment]
This should compile now and is more or less complete. I'm having a problem with my build.bat and literally just can't test it. If someone else can test and make sure everything is alright and let me know any problems, that would be helpful. If not I'll try to test it tomorrow morning before the planned tests if I can get my stuff working again.

**Review by ProfessorPopoff — COMMENTED** [review]
Should probably remove all the facewrap/halfwraps. They're legacy f13.

**Comment by Hekzder** [comment]
> Should probably remove all the facewrap/halfwraps. They're legacy f13.

wtf

**Pull request merged**
