### PR TITLE
the deadpan-depisstaining washing machine-ening party up edition

### PR DESCRIPTION
**Pull request by TheRealScarHomie**
## About The Pull Request

Adds in functional washing machines, only some on the map work, you can put stuff in and it cleans it, also completely changes a things sprite from dirty to clean if set, currently theres only one courtesy of our staticmainer Deadpan.

https://github.com/Mojave-Sun/mojave-sun-13/assets/63623569/35391991-456a-4166-aa1d-53d1a89d77d5

ADDITIONAL TWEAKING:

Epic new shawl sprite:
image
debate in comments below!!!!!

Handcuffs now work and are visible on the playa (phonky)

### CODE REVIEW

**Comment by ProfessorPopoff** [comment]
`[16:48:02] Runtime in other_mobs.dm, line 10: attack_hand_secondary did not return a SECONDARY_ATTACK_* define.
proc name: right click attack chain (/mob/living/proc/right_click_attack_chain)
usr: ProfessorPopoff/(Stephany Richardson)
usr.loc: (wasteland (38,60,3))
src: Stephany Richardson (/mob/living/carbon/human)
src.loc: road (38,60,3) (/turf/open/floor/plating/ms13/ground/road)
call stack:
Stephany Richardson (/mob/living/carbon/human): right click attack chain(the industrial washing machine (/obj/structure/ms13/storage/washingmachine/industrial), /list (/list))
Stephany Richardson (/mob/living/carbon/human): UnarmedAttack(the industrial washing machine (/obj/structure/ms13/storage/washingmachine/industrial), 1, /list (/list))
Stephany Richardson (/mob/living/carbon/human): ClickOn(the industrial washing machine (/obj/structure/ms13/storage/washingmachine/industrial), "icon-x=19;icon-y=10;right=1;bu...")
the industrial washing machine (/obj/structure/ms13/storage/washingmachine/industrial): Click(road (38,61,3) (/turf/open/floor/plating/ms13/ground/road), "mapwindow.map", "icon-x=19;icon-y=10;right=1;bu...")
ProfessorPopoff (/client): Click(the industrial washing machine (/obj/structure/ms13/storage/washingmachine/industrial), road (38,61,3) (/turf/open/floor/plating/ms13/ground/road), "mapwindow.map", "icon-x=19;icon-y=10;right=1;bu...")
`

**Comment by ProfessorPopoff** [comment]
Right click on a laundry machine that doesn't work or summin

**Comment by Mannybrado** [comment]
Hi 😃

**Comment by TheRealScarHomie** [comment]
> `[16:48:02] Runtime in other_mobs.dm, line 10: attack_hand_secondary did not return a SECONDARY_ATTACK_* define. proc name: right click attack chain (/mob/living/proc/right_click_attack_chain) usr: ProfessorPopoff/(Stephany Richardson) usr.loc: (wasteland (38,60,3)) src: Stephany Richardson (/mob/living/carbon/human) src.loc: road (38,60,3) (/turf/open/floor/plating/ms13/ground/road) call stack: Stephany Richardson (/mob/living/carbon/human): right click attack chain(the industrial washing machine (/obj/structure/ms13/storage/washingmachine/industrial), /list (/list)) Stephany Richardson (/mob/living/carbon/human): UnarmedAttack(the industrial washing machine (/obj/structure/ms13/storage/washingmachine/industrial), 1, /list (/list)) Stephany Richardson (/mob/living/carbon/human): ClickOn(the industrial washing machine (/obj/structure/ms13/storage/washingmachine/industrial), "icon-x=19;icon-y=10;right=1;bu...") the industrial washing machine (/obj/structure/ms13/storage/washingmachine/industrial): Click(road (38,61,3) (/turf/open/floor/plating/ms13/ground/road), "mapwindow.map", "icon-x=19;icon-y=10;right=1;bu...") ProfessorPopoff (/client): Click(the industrial washing machine (/obj/structure/ms13/storage/washingmachine/industrial), road (38,61,3) (/turf/open/floor/plating/ms13/ground/road), "mapwindow.map", "icon-x=19;icon-y=10;right=1;bu...") `

fixed

**Comment by Hekzder** [comment]
laundryening part 1

**Pull request merged**
