### PR TITLE
Mumbleboopening

### PR DESCRIPTION
**Pull request by ProfessorPopoff**
## About The Pull Request

This PR adds in the superior MUMBLEBOOPS system... No relation to the babble of Septic, surely...

## Why It's Good For The Game

https://user-images.githubusercontent.com/51188571/184249386-b7ba64d6-5fad-4ebe-92df-404fa1f4654f.mp4

https://user-images.githubusercontent.com/51188571/184249418-d4d88483-4755-4821-9ad8-c013696b7b9d.mp4

https://user-images.githubusercontent.com/51188571/184249467-a9de2709-8cc9-436f-b136-cc6d065fe400.mp4

No, I won't cut or edit this footage. You'll have to figure it out on your own. What is presented is what this PR is, a whole lot of booping...

There's some placeholder sounds in, also from Septic. No, there's no voice customization for now. 

## Changelog

cl:
add: mumbleboops
del: soundless speech
add: soul

### CODE REVIEW

**Comment by TheRealScarHomie** [comment]
holy shit its back

**Comment by ChungusGamer666** [comment]
hero

**Comment by AndrewL97** [comment]
@ProfessorPopoff send it

**Comment by ProfessorPopoff** [comment]
I webedited. it no longer has conflicts now.

**Comment by ProfessorPopoff** [comment]
it broke

**Comment by ProfessorPopoff** [comment]
Okay so basically. As of a year ago this was ready to merge. It is now working again. Though the voices are quite inconsistent and limited. We need to come to an agreement on a voice type that is ubiquitous enough to be made multiple of and unique without being annoying. I like that it's sort of pseudo-TTS but it's also poor quality audio with a lot of background grain. But I'd also still be open to something that is a little more subtle.

**Comment by Hekzder** [comment]
Okay, this is epic.

**Pull request merged**
