### PR TITLE
Supermarket Redo

### PR DESCRIPTION
**Pull request by Sinbest**
## About The Pull Request

Completely redoes the supermarket to not look like somebody spilt coffee all over the blueprints and the construction crew assumed the stain was apart of said blueprint.

Ground floor:

image

Second floor/roof

image

EDIT: 
I am aware I have missed the basement, unfortunately, because the existence of the basement was not pointed out until after I was done with the building, there is no space to put it that wouldn't involve destroying the sewers in some matter. (see image below)

image

EDIT 2:
The basement issue has been fixed by moving all of the basement loot upstairs. This was the only fix I could think of that didn't involve destroying the sewers or the supermarket. The basement has been deleted.

## Why It's Good For The Game

The ugly drink spill shaped supermarket is now gone and has been replaced by something that doesn't look completely crap

## Changelog

:cl:
add: Added new mechanics or gameplay changes
add: Added more things
expansion: Expands content of an existing feature
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

### CODE REVIEW

**Comment by Sinbest** [comment]
image

Mistake fixed.

**Comment by Sinbest** [comment]
fuck i forgot about the basement and the stairs are wrong

**Comment by ProfessorPopoff** [comment]
Hello there! So there's been quite some talk about this change in the mapping channel, as you know. Opinions discussed elsewhere- here's the issues that are directly wrong with the area itself. 

image
What do these doors hinge to? Avoid putting doors and windows right up next to each other like that

image
The south wall strip is very cursed. It's the nature of the north facing sprite, and probably shouldn't stay.

image
Avoid using multiple wall mounts on the same wall space like this, unless you're absolutely positive it won't look bad. First aid kits and lights _definitely_ don't work well.

image
I guess this was built by a wastelander as a mini-shack in the middle of it, but it stands out harshly to me, personally. I'd have a section wastelanders took over elsewhere, instead of a random shack in the middle. It's just... off.

image
Laying sin city. Also, players obviously won't open the ghoul fridges up after the first swing around. It'd help if there was a guaranteed spawn of some sort in there, to really TEMPT them into doing it.
image
This whole area in general is a bit off- Why would it be on the west side, when the kitchen and walk-in freezer is on the opposite side? I'd condense that over east so they're together and theme the area. Otherwise it'll be all over the place .

image
Similar layering sin

image
Doors like this never work! They always look bad. I'd just leave the back room entrance open. 

image
image
Something seems to be... definitely different here.

I'm not one to spout the **IMPROVE DON'T REMOVE** bit, because sometimes removal is outright better. But I thought the little roof group was pretty quirky, and a way to justify putting weapon spawns in the supermarket- at the very last part, nonetheless. Speaking of end points, nicking the basement was definitely one of the moves. I'm not as offended about it as some others may be, but It's definitely a noteworthy change. In the end, it's not much of a loss in my eyes, as long as the dynamic of the old basement is put elsewhere. Higher loot/Higher risk area. Probably condensed a bit into the backroom itself.

That's all I really have to say about the technicalities about this PR. Opinions and chatter/conversation about flavour and whatnot are better left off in the mapper channels so we can discuss in real time. Thanks again.

**Comment by ProfessorPopoff** [comment]
I forgot to merge this after the checks finalized. But it's all good to go. I went ahead and fixed a few things I personally scuffed up and pushed it- But it looks alright. Aesthetics are definitely vastly different than they were before, but it's not a bad thing. There are some niche issues with it currently, but it's not something I'm going to go up in arms about, as it's been rectified well enough to justify merging this. Further work will probably be done on this later- specifically perhaps adding a lower level and bringing the roof area back.

**Pull request merged**
