### PR TITLE
MY FIRST PR

### PR DESCRIPTION
**Pull request by mrpibb4201337**
image
image
GIVE IT A LOOK OVER

### CODE REVIEW

**Comment by TheRealScarHomie** [comment]
wheres the bar

**Comment by BadAtThisGame302** [comment]
No Underground Bar, downvoted

**Comment by ProfessorPopoff** [comment]
Congratulations on your VERY FIRST PR. It broke everything. 

Install that funny mapmerge hook under tools/hooks/install.bat, that way we can avoid anything like this happening. Then, go ahead and update your PR to be based off the most recent commit.

**Comment by mrpibb4201337** [comment]
are you fuckin kidding me

**Comment by mrpibb4201337** [comment]
ok

**Comment by mrpibb4201337** [comment]
no

**Pull request closed without merging**
