### PR TITLE
The tweakening (lets you put twohanders on the suit slot)

### PR DESCRIPTION
**Pull request by Sparrowbird611**
## About The Pull Request

Lets you put most twohanded weapons (spears, sledgehammers, drylander axe) on the suit slot like guns.

## Why It's Good For The Game

Now people like the raider enforcer, vet legionnaires, and dryland hunters don't have to drop their epic melee weapons to use their rifles.

Also because hekzder told me we could have this when I code it.

## Changelog

:cl:
add: You can now put twohanded weapons in your suit slot.
/:cl:

### CODE REVIEW

**Comment by Sparrowbird611** [comment]
and yes I tested this.

**Comment by ProfessorPopoff** [comment]
We were okay with this. It's just that there's no worn states for them. So it's harder to tell if a guy is packing a literal bumper sword at a glance, which should be quite obvious.

**Comment by Sparrowbird611** [comment]
> We were okay with this. It's just that there's no worn states for them. So it's harder to tell if a guy is packing a literal bumper sword at a glance, which should be quite obvious.

Fair, but I assumed it wouldn't be too big a deal to have the feature in now, given you can already put all these weapons on your back despite the lack of worn sprite. Most people will still end up holding their big melee weapon most of the time anyway because they'll want a rifle, letting them put it on the suit just gives them a little more flexibility.

If you have to close this until there are worn sprites then that's fine.

**Comment by Sparrowbird611** [comment]
image
Gaming

**Comment by TheRealScarHomie** [comment]
merge!!!!

**Comment by ProfessorPopoff** [comment]
Shishkebabs and Throwing spears, as well as thermic lances lack worn states. I haven't seen any others.


Autoaxes AND thermic lances, when put into your suit slot, will DUPLICATE. 

image\

This is likely something to do with them REQUIRING two handing. Bit of a code conflict. You'll have to disable holstering for both of them.

**Comment by Sparrowbird611** [comment]
> Shishkebabs and Throwing spears, as well as thermic lances lack worn states. I haven't seen any others.
> 
> Autoaxes AND thermic lances, when put into your suit slot, will DUPLICATE.
> 
> image\
> 
> This is likely something to do with them REQUIRING two handing. Bit of a code conflict. You'll have to disable holstering for both of them.

Feature

**Pull request merged**
