### PR TITLE
Sends the green floor hospital demon back to it's hellish realm

### PR DESCRIPTION
**Pull request by Sinbest**
## About The Pull Request

The floors of the hospital are now blue again, as the Lord God intended. (and I did some other minor changes)

## Why It's Good For The Game

Things looking good is good.

## Changelog

:cl:
tweak: changes the hospital
/:cl:

### CODE REVIEW

**Comment by Hekzder** [comment]
Speed merge

**Comment by ProfessorPopoff** [comment]
I'm not going to really hold it back because of personal preference- But why not have the floor tiles be something like the small or large white tiles, instead of the navy ones?

**Comment by Sinbest** [comment]
> I'm not going to really hold it back because of personal preference- But why not have the floor tiles be something like the small or large white tiles, instead of the navy ones?

Already tried that, it looks ugly as hell.

**Comment by ProfessorPopoff** [comment]
Concerns addressed. Thanks for the help, merging.

**Pull request merged**
