### PR TITLE
Mammoth Clinic Redo

### PR DESCRIPTION
**Pull request by Sinbest**
## About The Pull Request

Redoes the Mammoth Clinic to be more logical.

Before:
image

After:
image

## Why It's Good For The Game

Realism = good

## Changelog

:cl:
edit: Mammoth
edit: Mammoth_above
/:cl:

### CODE REVIEW

**Comment by ProfessorPopoff** [comment]
I only really have two comments to put out here, otherwise this looks very nice.

image
The rooms shouldn't have windows like this, otherwise people can cheese the handies and get everything in there essentially for free.

image
There's not too much of a need to place the broken bulbs manually, since there's a chance for lights to be broken on initialization. It might end up being pretty dark in there. I'd probably say just roll it back to the intact variant and it should come out pretty nice.

Thanks for the help again. Fix the first one in particular and i'll be able to merge it.

**Comment by Sinbest** [comment]
Give me a moment.

**Comment by Sinbest** [comment]
Ok, the issues should be fixed

**Comment by ProfessorPopoff** [comment]
Everything looks fine and requests are fixed. Thanks again. Merging.

**Pull request merged**
