### PR TITLE
KILLS SOUL. Removal of TG maps and minigames and stuff...

### PR DESCRIPTION
**Pull request by ProfessorPopoff**
## About The Pull Request

As the title says, this PR kills soul. This PR removes TG maps... All of them?

It also removes CTF and Mafia ghost stuff. 

## Why It's Good For The Game

It might not even be mergeable. It's an old branch. check it out!

### CODE REVIEW

**Comment by TheRealScarHomie** [comment]
um you accidentally deleted eagle lakes

**Comment by ma44** [comment]
?

**Comment by ProfessorPopoff** [comment]
this PR was made with us removal of all TG things in mind and us not commenting MS13 edit on every little thing, it's not set up to necessarily adhere to our... current standards? idk. figure it out.

**Comment by SeeminglyTypicalUsername** [comment]
bro but what if I wanted to play mafia,.,.,

**Comment by ProfessorPopoff** [comment]
yeah ok buddy

**Pull request closed without merging**
