### PR TITLE
Labels for Doors

### PR DESCRIPTION
**Pull request by bardinatavern4**
Exactly what it sounds like. You can check in SDMM for each door. All it does is change the name of doors in the big faction hubs so they're a little easier to navigate. For instance, the area the mayor spawns now has the doors labeled "Mayor's Office". 

Areas affected by this:

NCR Mainbase
Raider Town
Vault Town
BOS Mainbase

Any area that isn't actively used by a faction was left untouched. This is just so people in RP centers can find their way around a bit easier. 

I've also tried to differentiate areas with similar purposes by giving them different door names. The BOS medical center is the Medbay, the Town is the Doctor's Office, the NCRs is the Makeshift Triage, and Raiders is the Doc Sawbones. This is to make it a little easier to differentiate them instead of naming them all "The Medbay" or something.

### CODE REVIEW

**Comment by bardinatavern4** [comment]
screenie
WOOOOOOOOOOAHHHHHHHHHHHHH LABELSSSSS!

**Comment by ProfessorPopoff** [comment]
I can actually look at this PR when you take it seriously. Remove the area edits- Remove the base TG icon edits, and remove the troll bar sign var edit.

**Comment by Sinbest** [comment]
Please keep the area edits, the base TG icon edits, and the troll bar sign var edit.

**Comment by bardinatavern4** [comment]
area edits were unintentional and probably caused by misclicks. it'll take me a bit to go through and fix every one.

I can't believe the sign was 1984'd. Enclave Door #1 is HRP and critical for player immersion....

**Comment by bardinatavern4** [comment]
having now doublechecked, the 'area edits' seem like a Github fuckup. For instance:
image
Here it says that the 'Doc Sawbones' office door and the floor below it are a new change.
image
here it is on my SDMM

but if we go check the map posted in #tips a few days ago we see...
image
That door was already there, but for some reason Github is saying it's a new change. I'm not sure what's up with that, but there don't appear to be any actual area changes, just Github strangeness.

**Comment by ProfessorPopoff** [comment]
Unkempt and unclean. Requests haven't been fulfilled, as the PR is still littered with goofy and unnecessary names, and there is a lack of activity on it, as well as said author not responding to questions in regards to the PR. I'll be closing this now.

**Pull request closed without merging**
