### PR TITLE
Fixes PA recoil and mumbleboops

### PR DESCRIPTION
**Pull request by Hekzder**
## About The Pull Request

Title I should have done this earlier

## Why It's Good For The Game

yea

### CODE REVIEW

**Comment by Hekzder** [comment]
merge me

**Comment by ProfessorPopoff** [comment]
MAN. This PR stinks. I'll never merge it. Tch.

*Walks up my custom carved mahogany staircase

*gasps

*clutches my chest.


ohohlgkh.. jhrrt... my hear./t...


*falls down my mahogany wood custom carved staircase

*falls into the merge button

**Comment by Hekzder** [comment]
Oh good heavens!

**Comment by ChungusGamer666** [comment]
*starts vomiting
*dry heaves

**Pull request merged**
