### PR TITLE
vault town touchups chapter two (2)

### PR DESCRIPTION
**Pull request by Sinbest**
## About The Pull Request

touches up vault town, changes some areas, tries to compress the vault a bit

## Why It's Good For The Game

good is good

## Changelog

:cl:
add: Added new mechanics or gameplay changes
add: Added more things
expansion: Expands content of an existing feature
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

### CODE REVIEW

**Comment by Hekzder** [comment]
Nice pictures. Looks amazing.

**Comment by BadAtThisGame302** [comment]
Pictures?

**Comment by TheRealScarHomie** [comment]
Nice pictures. Looks amazing.

**Comment by bardinatavern4** [comment]
Nice pictures. Looks amazing.

**Comment by ProfessorPopoff** [comment]
Post images next time, Please.

image
image

I won't be looking this over or merging it until the current test are done with.

**Comment by Sinbest** [comment]
> Post images next time, Please.

I was tired as hell at the time, sorry.

**Pull request closed without merging**
