### PR TITLE
Draught general cleanup

### PR DESCRIPTION
**Pull request by Sinbest**
## About The Pull Request

Cleaning up Draught, in general.

Ranger outpost before:

police before

police 2 before

Ranger outpost after:

police after

police 2 after

More to come.

## Why It's Good For The Game

Draught is nicer.

## Changelog

:cl:
edit: draught
/:cl:

### CODE REVIEW

**Comment by mrpibb4201337** [comment]
draught 🤨

**Comment by Koshenko** [comment]
> draught 🤨

Shut up pibb.  Will let Original take a look at this.

**Comment by ProfessorPopoff** [comment]
Alright then. Ahead of the review, I appreciate you taking an interest in us! It's a rare occurrence someone wants to actually help out with something here, so I'll shake your hand on it. This is a pretty brief one. 

image
This door by the front desk is faced in the wrong direction. It's a really unintuitive system, I know. But this is how our doors are set up. 

image
Doors natively sit on the south. They change what direction they're propped as based on the dir variable. 1 (North) puts it on the north face, 8 (West) on the west, and 4 (East) - You can guess where. We have mirrored versions of the doors which flip the West/East orientation. You can make double doors on north/south facing doors, but it doesn't really work out well West/East.

image
I've got a few comments about this area. Pretty much just observations and you're not entitled to change them.
The payphones are solid, so if you wanted to add another one, i'd put it on the north face next to the other one or something. That way it's not making a choke point out of that entrance area like that. Similarly themed- the double doors were also there to prevent a hard choke point, so that more than one person can squeeze through and out of this relatively cramped base, the same goes for that initial 'waiting room' area. Having just one door on either face can really bog down the mobility of it, and will make any intruder scenario a nightmare. If you care to help me out, the front sidewalk is actually uneven as well, with a sidewalk extending out past the wall on the south but not the north.

image
This doorway could potentially make any jailbreaks a REAL issue. Don't get me wrong, I love watching people suffer... But to have this many layers of doors is cruel. Plus it's got a better flow if it's just a straight hallway.  Not to mention the value of imprisoned people yelling to get let out at people just trying to walk upstairs is funny. I'd hate to completely shut them off.

I mostly just need that door flipped back around and prison hallway cleared, and if you agree with any other points I've made you can feel free to adjust to them. Nicking that sidewalk overhang or adjusting it would also be greatly appreciated. 

Thanks again for taking interest.  Feel free to ping me on discord for any questions about anything in the future.

**Comment by Sinbest** [comment]
Alright, I'll fix the door issue.

**Comment by Sinbest** [comment]
Door Issue _should_ be fixed.

**Comment by ProfessorPopoff** [comment]
Everything looks fine now. Thanks for the help. Merging.

**Pull request merged**
