### PR TITLE
SmigglefixesTHREE - WOAH! - WOWZER!

### PR DESCRIPTION
**Pull request by TheRealScarHomie**
## About The Pull Request

fixes the techno bug (smoking now = false, and chain smokah can go down)

### CODE REVIEW

**Comment by ChungusGamer666** [comment]
fake chungus goblinator

**Comment by TheRealScarHomie** [comment]
can it broad

**Comment by TheRealScarHomie** [comment]
MERGE THIS SHIT!

**Comment by ProfessorPopoff** [comment]
@Hekzder

**Comment by ProfessorPopoff** [comment]
gas

**Pull request merged**
