### PR TITLE
Update Time: Machinery to People

### PR DESCRIPTION
**Pull request by EdwardNashton**
Added a recorders and server racks all over the city (Some of them will be on screens below)

image

image

image

image

Slightly changed a "Cheap Motel" near Police Dept.

image

image

Slightly changed Police Dept.

image

image

Slightly updated Chemical Factory and Weather Station.

image

image

image

Slightly updated Water Treatment.

image

### CODE REVIEW

**Comment by BadAtThisGame302** [comment]
There's like TG shutters and TG remains on the fourth picture, I suggest replacing/removing them.

**Comment by Snowyypanda** [comment]
> There's like TG shutters and TG remains on the fourth picture, I suggest replacing/removing them.

one day we will have our own baron'd shutters, we can only dream of that day

**Comment by Sinbest** [comment]
> > There's like TG shutters and TG remains on the fourth picture, I suggest replacing/removing them.
> 
> one day we will have our own baron'd shutters, we can only dream of that day

we have custom shutters right now, go look

**Comment by EdwardNashton** [comment]
> There's like TG shutters and TG remains on the fourth picture, I suggest replacing/removing them.

We will replace it later, it requires some efforts because, uh, there's TONS of the shutters, many of them has "id" edits.

**Comment by BadAtThisGame302** [comment]
> > There's like TG shutters and TG remains on the fourth picture, I suggest replacing/removing them.
> 
> 
> 
> We will replace it later, it requires some efforts because, uh, there's TONS of the shutters, many of them has "id" edits. 

I mean you're already touching by that area... so why not just replace like those 4 TG assets?

**Comment by EdwardNashton** [comment]
> > > There's like TG shutters and TG remains on the fourth picture, I suggest replacing/removing them.
> > 
> > 
> > We will replace it later, it requires some efforts because, uh, there's TONS of the shutters, many of them has "id" edits.
> 
> I mean you're already touching by that area... so why not just replace like those 4 TG assets?

Technically I've touched many areas. I've changed shutters in some of them, but not on every area.

**Comment by Hekzder** [comment]
Why does the police station have a garage door/shutters into what is presumably either the evidence room or armory from the outside?

**Comment by EdwardNashton** [comment]
> Why does the police station have a garage door/shutters into what is presumably either the evidence room or armory from the outside?

Because this is indestructible shutters that covers a windows. 
So, people will not broke the windows and walks in Armory through that room, bypassing all the mobs.

**Comment by ProfessorPopoff** [comment]
Hi. I've only really noticed four things here... Perhaps this is a result of you doing **A PR CHANGING THIS MANY LOCATIONS.**

But it's fine... I've skimmed it enough, I suppose.

image
I can really appreciate the fact you kept a TGstation microscope in the chem manufacturing building, but it should go. 

image
The server in this corner of the water treatment plant- It's facing directly against a table and a terminal. _That's not how that works._ 

image
I didn't notice this in a prior PR, but it's a bit strange having windows down into the jail cells, is it not? Hm. The windows would be funnier if you moved them over by one tile, so it was centered on the stairwell itself, that way people can jump in, but can't get out easily. 

image
This last one is a bit more on maybe... a nit-picky side? Stay clear of what?

You know me, I like to have a bit of environmental interaction. So using turfs like these everywhere like we've sort of been doing makes them just another tile. Which they're not- They've got things to say! We should probably start limiting these to doors/machinery or whatever else is along those line. 

Osha may be harsh, But I don't think they're even going to tell you to remain clear of a table at all times.

Thanks again anyways. Try not to do a PR like this again.

**Pull request merged**
