### PR TITLE
makes glass shards edible

### PR DESCRIPTION
**Pull request by ChungusGamer666**
## About The Pull Request

https://www.youtube.com/watch?v=TsQw0tmR7z8

## Why It's Good For The Game

https://www.youtube.com/watch?v=TsQw0tmR7z8

## Changelog

:cl:
add: Eat glass
/:cl:

### CODE REVIEW

**Comment by ProfessorPopoff** [comment]
that's 🧢

**Comment by ChungusGamer666** [comment]
its 📠

**Comment by TheRealScarHomie** [comment]
what

**Comment by ChungusGamer666** [comment]
merge the fucken pr

**Comment by ProfessorPopoff** [comment]
Watch this drive.

**Pull request merged**
