### PR TITLE
[PROJECT] Mojavemed: Because I fucking hate myself

### PR DESCRIPTION
**Pull request by ChungusGamer666**
## About The Pull Request

Porting Bobmed but I try to make it fit this setting better etc.

Now you might say, "This should be done piecemeal! This PR is not atomized!"
And I shall say, fuck off. I hate you. Your presence bothers me.
I will do *most* things on this PR alone.

## Why It's Good For The Game

https://user-images.githubusercontent.com/82850673/222480911-6a6d4fe2-a43d-4da6-90f3-938a923d8fe1.mp4

## Changelog

I will not dare to bother with documenting every change here.

### CODE REVIEW

**Comment by ChungusGamer666** [comment]
will start working on this as soon as there is staff consensus on what to do with medical
https://www.youtube.com/watch?v=UcyNHuW01vY

**Comment by ChungusGamer666** [comment]
NGMI until the final tg merge

**Comment by ChungusGamer666** [comment]
image

**Comment by ChungusGamer666** [comment]
we are so back

**Comment by githubuser4141** [comment]
it's SO joever

**Pull request closed without merging**
