### PR TITLE
Vault touchsups and a sign plus more

### PR DESCRIPTION
**Pull request by Sinbest**
## About The Pull Request

Touches up the vault a bit, and also touches up the civilian fallout shelter a tiny bit as well.

Vault

image

image

Fallout Shelter

image

image

image

image

(will remove the two extra helmets if asked, I added them because I'm half sure they are unobtainable at the moment)

## Why It's Good For The Game

Things looking good is good

### CODE REVIEW

**Comment by ProfessorPopoff** [comment]
Hi! Sorry for the delay. I've been busy.

This is way too much soul- Don't place stuff like this! 
image

I really have a problem with are the static spawn helmets, Please remove them!
image
image

image
While you're working in this area, you should pop those trays out of existence for me, since you're so awesome

Also, why had you replaced the tile under the airlocks here? A bit out of place in my eyes. 
image

The only comment about soul I have is the little waiting area for the Mayor's office. You can't really just walk up to the waiting desk because- it's behind a locked door! 
image
If anything, I'd remove the initial door or something and just leave it open. 
image

Thanks again, I can merge once the requested changes are addressed.

**Comment by Sinbest** [comment]
> This is way too much soul- Don't place stuff like this!

...

What's the point of the fallout shelter signs if not to designate the fallout shelter?

>I really have a problem with are the static spawn helmets, Please remove them!

Alright.

>Also, why had you replaced the tile under the airlocks here? A bit out of place in my eyes.

I did that there because I did that for all the airlocks.

**Comment by ProfessorPopoff** [comment]
>What's the point of the fallout shelter signs if not to designate the fallout shelter?

I think you'll have to evaluate your social status if you don't understand what I was getting at here. You've placed it inside of a wall- It doesn't even make sense, it doesn't match up with the wall. Half the point of our wall's perspective is to not do stuff like this. It sucks that the bunker is oriented like that, but I'd MUCH sooner rework the whole location than let a sign get placed in a wall like this.

> I did that there because I did that for all the airlocks.

I hadn't noticed for the others, but I get it now. It's a lot more subtle on the other airlocks. It's fine, then.

**Comment by Sinbest** [comment]
> > What's the point of the fallout shelter signs if not to designate the fallout shelter?
> > I think you'll have to evaluate your social status if you don't understand what I was getting at here. You've placed it inside of a wall- It doesn't even make sense, it doesn't match up with the wall. Half the point of our wall's perspective is to not do stuff like this. It sucks that the bunker is oriented like that, but I'd MUCH sooner rework the whole location than let a sign get placed in a wall like this.

Ah, that makes sense.

Also,
> > You've placed it inside of a wall

 I thought that's how we did things on walls due to being tired.

**Comment by ProfessorPopoff** [comment]
Requested changes were addressed. Thanks again, merging.

**Pull request merged**
