### PR TITLE
Distant fire sounds

### PR DESCRIPTION
**Pull request by ChungusGamer666**
## About The Pull Request

https://www.youtube.com/watch?v=0XgPWaYmmsU
image

## Why It's Good For The Game

ambiance or some shit

## Changelog

:cl:
soundadd: Distant gun sounding, so cool!
/:cl:

### CODE REVIEW

**Comment by ChungusGamer666** [comment]
untested gimme a moment

**Comment by ChungusGamer666** [comment]
it works

**Comment by ChungusGamer666** [comment]
https://user-images.githubusercontent.com/82850673/235388837-93dad96f-be01-4600-83a3-aa97bf2bcbf0.mp4

**Comment by ChungusGamer666** [comment]
HEEEEEEEEEEEEEEELP

**Comment by TheRealScarHomie** [comment]
👺

**Pull request merged**
