### PR TITLE
Draft of a draft: Last Chances!

### PR DESCRIPTION
**Pull request by githubuser4141**
## About The Pull Request

Simply, human hearts now produce epi when their host reaches crit. Makes dungeoneering if you're on a shite connection more viable! :)

## Why It's Good For The Game

People don't have to ghost out when they're miles into a dungeon and reach crit because that's cringe! T-51b Paladins won't die to a literal mouse because their internet crashed! 💯 

Draft for now because it's shitcode and flavour texts & hunger management aren't done
It's ALSO a webedit I don't have the bandwidth to DL the entire github rn
## Changelog

:cl:
balance: People are a teeny bit more resilient to death now.
/:cl:

### CODE REVIEW

**Comment by TheRealScarHomie** [comment]
wrong codebase buddy

**Comment by Hekzder** [comment]
Who are you and why are you webediting base code improperly

**Comment by githubuser4141** [comment]
Sorry. Will have a look into doing it properly when, or if I have the time. Bit busy with IRL at the moment and don't have a lot of time to play spess.

**Comment by ProfessorPopoff** [comment]
Code state aside, I can see why you'd want this. But It's not the right approach to it.

Something that's been proposed before is making people who are above a certain health _slowly_ regenerate over time. This could be given modifiers such as being next to a campfire, sitting down, or laying on a bed. 

Giving people passive healing simply because they're in crit is bound to cause issues. I also foresee this making people execute others more often, so that they don't ever get back up. 

Chances are if you went down in a dungeon, it's because you went alone.  Having OOC stuff affect your round is unfortunate, but we can't compensate for that by making death from mobs not a factor. 

Otherwise, I do appreciate the interest in contributing.

**Comment by githubuser4141** [comment]
> Code state aside, I can see why you'd want this. But It's not the right approach to it.
> 
> Something that's been proposed before is making people who are above a certain health _slowly_ regenerate over time. This could be given modifiers such as being next to a campfire, sitting down, or laying on a bed.
> 
> Giving people passive healing simply because they're in crit is bound to cause issues. I also foresee this making people execute others more often, so that they don't ever get back up.
> 
> Chances are if you went down in a dungeon, it's because you went alone. Having OOC stuff affect your round is unfortunate, but we can't compensate for that by making death from mobs not a factor.
> 
> Otherwise, I do appreciate the interest in contributing.

Yeaaaah. I had the idea that, when finished properly, it'd:

- Won't actually save you from a ghoul that bleed-wounds you (this was tested, and obvisously the dungeon comment is a joke. - I don't think there are any hostile mobs that either don't bleed-wound or don't kill in crit.)
- Ideally, should knock you out, prevent you from fighting, etc etc after it's applied, or the crit code itself should handle it -- to discourage straight execution.
- Has consquences (organ damage, assuming there's code for that in TG.) So people don't crit themselves for free healing reagents.
- At the day's end it shouldn't _actually_ let you solo a dungeon, or have consquence-free combat. That'd be goofy as fuck, yes, unless the dungeon is guarded by **mouse mobs**. It's definitely not the intention to let you simply crawl away, rest and re-do until you win by attrition. [Luckily, this would be difficult to do with aggressive AI and bleed-wounds.]

**Comment by ProfessorPopoff** [comment]
> * Won't actually save you from a ghoul that bleed-wounds you (this was tested, and obvisously the dungeon comment is a joke. - I don't think there are any hostile mobs that either don't bleed-wound or don't kill in crit.)

There's a bunch of them, actually. Namely robotic mobs. Pincher handies, Protectrons, Gutsies, Sentry bot, Robo brains (already kind of suck but they're part of the list too). Having something like this would basically make you HAVE to want to die to these things. 

I don't necessarily know if giving organ damage to people because they stood back up is a good thing.

For mobs finishing you off- It's sort of iffy. The vast majority of mobs do **not** currently attack you until you're dead. This is because we were mid-process of transferring our mobs to the basic mob platform and then promptly realized that TG stopped development on them and they lack many of the features that make simple mobs so customizable, including customization of what state they'll continue to attack you until.

**Comment by ProfessorPopoff** [comment]
I don't mean to push it away, there's just a lot of factors we need to look at before having something like this in.

**Comment by githubuser4141** [comment]
That's fine, I probably shouldn't have time to mess about on spessmans anyway 🤷 . Yeah, you're right.
Hm, maybe burn / fracture wounds should cause fluid, blood or infection loss/chance?

The idea with O-D is it wouldn't severely affect someone until it reached a certain threshold, and could be treated by surgery. IMO, you shouldn't be able to loop crit > a buddy applies 1 suture to you more then a few times without _something_ to show for it.

OK. I'll be honest, this was a hare brained idea to put up a "WIP draft of a _potential way to go about something._" And it's really, just a waste of time to read over, and holy motherfucker that's awful code. I actually cringed when I saw this and remembered it was a thing I posted. So, I think I'll just go ahead and close it. 🔢 Have a good day. 👍

**Pull request closed without merging**
