### PR TITLE
Gridventory Stuff

### PR DESCRIPTION
**Pull request by Hekzder**
## About The Pull Request

Basically puts down sizes for storage and for items for all of our stuff for gridventory. As well as fixing some bugs with it as well. Also makes some minor adjustments to some other things, like sizes of crafting material stacks and making our own children of TG medical tools (to eventually be replaced by our own medical tools). 

## Why It's Good For The Game

Gridventory is cool but needs to be tweaked to fit properly into THE VISION.

### CODE REVIEW

**Comment by Hekzder** [comment]
Heavily WIP for now. Need to get in some bug fixes, finalize sizes for some other things, then test everything. Might be able to get this done by the end of the weekend or something.

**Comment by Hekzder** [comment]
This is as ready as it can reasonably be right now. The no worn access flag does not currently work for us due to it fucking up round start items for jobs. Given that I'm really not sure where to even begin on what we need to port over from Septic Shock to make it work, I don't see myself finding time to do this before the tests.

If someone else can save the day, great, I'll adjust some stuff around with storage sizes and access accordingly, but otherwise things will stay as is with all backpacks being anywhere access and a 6x5 grid. Not ideal but it's what we're working with for the tests most likely.

**Comment by Hekzder** [comment]
This is good good to go now. #2044 fixed the no worn access stuff, shoutout @ChungusGamer666

**Comment by ProfessorPopoff** [comment]
ok

**Pull request merged**
