### PR TITLE
Advanced cannibalism mechanics

### PR DESCRIPTION
**Pull request by ChungusGamer666**
## About The Pull Request

I am the willing victim of a cannibal
She rips out my bones just like I'm an animal
And right when I'm feeling like my blood is drained
She calls it a game
But the wound that she leaves is unmistakable

## Why It's Good For The Game

https://fallout.fandom.com/wiki/Andale

## Changelog

:cl:
add: Cannibalism
/:cl:

### CODE REVIEW

**Comment by ChungusGamer666** [comment]
i still need to add baby back ribs (made from real baby) lemme draft this again

**Comment by ChungusGamer666** [comment]
ho.w convert to fdraft

**Comment by TheRealScarHomie** [comment]
its drafted

**Comment by ChungusGamer666** [comment]
the sprite for cooked ribs is literally a mcrib right now i can't be arsed

**Comment by TheRealScarHomie** [comment]
the what

**Comment by ProfessorPopoff** [comment]
the what

**Comment by ChungusGamer666** [comment]
the mcrib

**Comment by ProfessorPopoff** [comment]
image
..yup

**Comment by ChungusGamer666** [comment]
Let's Go Brandon

**Pull request merged**
