### PR TITLE
Gives everything but helmets/armour/suits slowdown and repurposes suit storage 

### PR DESCRIPTION
**Pull request by ProfessorPopoff**
It just felt like the right thing to do....

This PR doesn't include helmet/suit/armour equip delay as that's the area Hekzder is touching and he requested I didn't.

I can't really get a video of it, so instead I present a scenario:

Imagine putting on clothing in a TG codebase, but it takes 0.15 seconds to do it after you hit E.

This doesn't cover unequipping unfortunately. We'll have to figure that out later, but this is half the battle.

### CODE REVIEW

**Comment by Snowyypanda** [comment]
is there like a spreadsheet where we can see the changes?, i don't wanna go through files just to understand what's going on

**Comment by ProfessorPopoff** [comment]
> is there like a spreadsheet where we can see the changes?, i don't wanna go through files just to understand what's going on

There isn't, no. They're not very extensive changes. 

- Shoes are 1 SECOND
- Glasses are 0.15 SECONDS
- Gloves are 0.25 SECONDS
- Masks are 1 SECOND
- Gas masks are 2 SECONDS
- Neck attire (as limited as it is) is 1 SECOND
- Backpacks take 1 SECOND
- Underclothing takes 2 SECONDS

**Comment by ProfessorPopoff** [comment]
This PR now also includes repurposing of the "suit slot" to be more like a dedicated long weapon slot. This ensures the stability of peak cowboy roleplay. Previously it was impossible to stumble outside of your homestead at late night hours wearing only your hat and your long johns with a .44 slung over your dedicated gun shoulder... No more shall cowfolk be oppressed.

**Comment by ProfessorPopoff** [comment]
sad violin on that commit right there

**Comment by Hekzder** [comment]
Waiting for a spreadsheet on this PR

**Pull request merged**
