### PR TITLE
Backtracks on previous male baron verdict

### PR DESCRIPTION
**Pull request by ProfessorPopoff**
## About The Pull Request

This PR makes the Baron role exclusive to Female gendered characters. It will also randomize the hair to be a random colour, making them visually powerful among a crowd.

## Why It's Good For The Game

Diversity is always good. I've learned from my errors, and the only one that could change my mind is a certain someone that knows what needs to be done

image

### CODE REVIEW

**Comment by ProfessorPopoff** [comment]
Quite a wide variety of hair colour possibilities with an unsanitzed colour pick.  
image

**Comment by ChungusGamer666** [comment]
Original has officially lost his damn mind, we need to throw his ass back on F13

**Comment by QuartzMech** [comment]
Original, don't hold the server hostage like this.

**Comment by ProfessorPopoff** [comment]
> Original, don't hold the server hostage like this.

I'm just doing what should have been done long ago.

**Comment by BadAtThisGame302** [comment]
Finally a good PR made by Original never thought I'd see the day!

**Comment by Hekzder** [comment]
We'll definitely have to have some real discussion about this but I think this is the proper direction our server needs to be going. I'll bring it up at the next board meeting.

**Comment by CaputCapital** [comment]
> > Original, don't hold the server hostage like this.
> 
> I'm just doing what should have been done long ago

The Cheyenne Kifer character revamp on the far left though. There's a hidden message here in this PR.

**Pull request closed without merging**
