### PR TITLE
Add examine chat log and tarkov gridventory position fixes

### PR DESCRIPTION
**Pull request by ProfessorPopoff**
## About The Pull Request
This PR adds in soundboops. For every word in your sentence, it will play a little bloop/bleep to mimic you talking. Sounds are temporary until we get something better maybe, but the system is there. It's tied in to prefs, and modular so that we can give different mobs different sounds and whatnot.

Along with this, Tarkov/Grid storage now is out of the way a bit, so you can at least interact with the tiles near you.

This PR also makes you visibly examine things. That way other players can see where you're looking, and if you're eyeing up the platinum drip!

I'll see about adding a voice bloop toggle in prefs at some point.
## Why It's Good For The Game

Promotes immersion allegedly and gives players audio feedback to conversation and helps you get in the GROOVE perhaps.

### CODE REVIEW

**Comment by Mannybrado** [comment]
insane. insane. insane.

**Comment by mrpibb4201337** [comment]
"MUMBLEBOOPS"? really?

**Comment by ProfessorPopoff** [comment]
image
Added balloon alerts to looking.

This PR now also fixes the position of storage grids. You can actually see a bit, now.

**Comment by ProfessorPopoff** [comment]
Mumbleboops are dead. I'll port over Bob's eventually.

**Pull request merged**
