### PR TITLE
The deeteeeneining

### PR DESCRIPTION
**Pull request by Hekzder**
## About The Pull Request

This PR will basically rebalance almost everything we have in terms of damage and armor values, and also shake up the loot tables a bit too. It will completely overhaul armor by integrating the new armor system from #2066 and change values for basically all weapons, from lasers, to guns, to the infamous super sledge and the humble brick. 

This PR will also include lots of changes to wounds, mostly nerfs to make them not quite as uber deadly to make up for the fact that they are generally more common on our server than TG, and the DT system will make them a lot more consistent and less prone to RNG. 

A spreadsheet with proposed damage and penetration values [can be found here.](https://docs.google.com/spreadsheets/d/1Md1LpQRmf4SS4cbmE46LYTvYK8dz9wK0TmwWMOEUbNA/edit?usp=sharing)

A Google doc with proposed armor and armor tier values [can be found here.](https://docs.google.com/document/d/1ATqxmbCLmV5VbCIbI3CIXMFyXdyhe3W-ritP3QhqjRs/edit?usp=sharing) (Also includes faction armors)

## Why It's Good For The Game

DT is really cool and using it in a well balanced and implemented way is also really cool.

### CODE REVIEW

**Comment by Hekzder** [comment]
Heavily WIP for now. Basically just have values for guns and bullets, and some changes to wounds in right now.

**Comment by Mannybrado** [comment]
i see what you did there- deeteeening, because like damage threshold, thats so cool

**Comment by Hekzder** [comment]
Here is an overview of the changes to wounds for this PR:

**Bone Wounds**

Easier to dislocate a limb (moderate bone wound)

Brain trauma on severe bone wound nerfed moderately
Internal bleeding on severe chest wound made more common but bleeds for less. 

Slightly easier to get a critical bone wound on someone
Limp slowdown of a critical bone wound very slightly reduced
Internal bleeding on critical chest wound made much more common but bleeds for less.

**Slash Wounds**

All slash wounds bleed less

Moderate slash wound clots on it's own slightly slower
Severe slash wound clots on it's own slightly faster
Critical slash wound gets worse on their own at a much slower rate (critical slash wounds get worse instead of clotting when left untreated)

Severe and Critical slash wounds are somewhat easier to perform on someone

**Pierce Wounds**

All pierce wounds bleed less and have a substantially decreased internal bleeding modifier

Moderate pierce wound has a slightly increased gauze clot rate. 
Moderate pierce wound has more of a wound penalty (extra bonus to wound rolls on affected area)

Severe pierce wound has a slightly higher internal bleeding chance
Severe pierce wound has more a wound penalty

Critical pierce wound has a slightly increase gauze clot rate
Critical pierce wound has a moderately higher internal bleeding chance

**Burn Wounds**

Moderate burn wound has a slightly decreased wound penalty

Severe burn wound has a slightly decreased damage multiplier (15% from 20%)
Severe burn wounds become infected at a much slower rate
Severe burn wounds have slightly decreased flesh damage (easier to treat)

Critical burn wounds have a slightly decreased damage multiplier (25% from 30%)
Critical burn wounds become infected at a moderately slower rate
Critical burn wounds have a moderately decreased wound penalty
Critical burn wounds have slightly decreased flesh damage (easier to treat)

**Comment by Hekzder** [comment]
[Here is an overview](https://docs.google.com/spreadsheets/d/1Ea1j14qodMKcu1UXRqrxLEBvvYEMbfGQR9z9gehFWp0/edit?usp=sharing) of the changes impending for loot distribution/tiers for guns, as well as their intended stats.

Most notable changes is that almost all non-automatic weapons are slower. This is to keep time to crit within reasonable levels since combat will generally become more deadly with coverage based protection and having it so you, for the most part, either take the full damage of something or none of it. This also should make automatic weapons _feel_ a bit faster since they will be, relative to everything else. 

Almost all of the SMGs were moved down a tier, a lot of the tier 4 SMGs into tier 3 and the 9mm SMG into tier 2, since the armor changes make pistol calibers overall much weaker. Tier 2 is overall a bit bigger and Tier 4 is a bit smaller, Tier 1 and 3 are about the same size. 

Laser weapons fire slower but deal on average about the same damage, laser weapons and ammo will also be a bit more common as laser weapons have been dispersed a bit more evenly throughout the tiers. Plasma weapons also fire slower but deal a bit more damage on average and have very high wound bonus for melting flesh. Plasma weapons and ammo will be quite a bit more rare as they've all been pushed into Tier 3+, mostly Tier 4. 

It's hard to really explain everything but I can answer questions in Discord.

**Comment by ProfessorPopoff** [comment]
merging it.......... NOW.........../

**Pull request merged**
