### PR TITLE
Grand Food/Cooking/Nutrition Overhaul

### PR DESCRIPTION
**Pull request by TheRealScarHomie**
# About The Pull Request

Completely overhauls the food, cooking and effects of each for a deeper, more survival based and esoteric gaming experience.

# Idea/Implementation

Idea not fully there, just notes and ideas, code to boot but heres the gist of it,

## Nutrition

Firstly a nutrition system that rewards balance of foods, giving faster health regen when eating and also maybe a slightly higher health pool, (will be more useful in future), people who dont balance this and just eat scraps off the floor wont see a downside, they just wont have an upside beyond not starving. Rewarding creativity and balance of consumption throughout the round. 

Different factions may start with different levels of nutrition (Due to their access to variety, etc.) Most likely with wasters having the lowest due to being bums barely scraping by.

Nutrition Types are:

MEAT (1<<0)
VEGETABLES (1<<1)

GRAIN (1<<4)
FRUIT (1<<5)
DAIRY (1<<6)

SUGAR (1<<9) (good in moderation)

JUNKFOOD (1<<3) (bad nutrient, dont have too much!)

## Cooking/Meals

Secondly, the days of microwaves are gone, fully machine based and use based processing of foods and construction of them, all clicking and interactive, full customizability on a 1-4 ingredient based meal system, these meals function as combos, with taste palettes and things that work well with each other, and things that dont, better food combos give better short term buff affects to regeneration and stuff. 

For example a burger with 4 identical meat slabs on it will fill you up and give you nutrition, it just wont have much of a positive side affect beyond stopping starvation.

There will be 7 kinds of meals to make:
Soup (Multiple ingredients in a bowl (with water)
Stew (Multiple ingredients in a bowl (no water)
Sandwich (Multiple ingredients on bread)
Burrito (Cooked Wrap)
Cake (Multiple ingredients with sweet dough)
Pie (Multiple ingredients on pie dough) (types, normal/reagent)
Plated meal (stuff on plate)

These may give boosts to the type of nutrition depending on the meal, to make all unique and stuff, only certain ingredient types will work with certain meals and shit.

These products will be created with a modicum of slapcrafting and three new machines, through grilling, boiling and frying (maybe baking)

## Other

Probably a lot of unmentioned stuff here because design documents are for chumps,

Food poisoning chance for unsanitary handling of food, dragging some meat 80 miles across the wasteland, etc.

Probably some other shit so this can get really fleshed out.

# Checklist

- [x] inworld sprite code?
- [x] utensil sprites
- [x] randomised cans/canned food
- [ ] ingredient sprites
- [ ] machine sprites
- [x] meal sprites
- [ ] code in ingredients
- [ ] code in machines
- [ ] code in nutrition
- [ ] dmi wrangling
- [ ] nutrition functionality
- [ ] tastes functionality
- [ ] food poisoning
- [ ] more shit I forgot

byeah

### CODE REVIEW

**Comment by ProfessorPopoff** [comment]
Bad.

**Comment by ProfessorPopoff** [comment]
Not yet

**Comment by ProfessorPopoff** [comment]
don't close

**Comment by Hekzder** [comment]
Closing per Original Idea's request

**Pull request closed without merging**
