### PR TITLE
THE PLASTIC CHAIRS; ant village of mammoth and some miscellaneous stuff

### PR DESCRIPTION
**Pull request by mrpibb4201337**
i added things in z3 of the ant village mining place, removed some things like the bombshell poster and the bola with no sprite in z2, and also replaced the hostile trees in front of a building with normal ones and put a hardware spawner in the hardware store. also there was random gibs in the mountain lol :) :P :^) :D

### CODE REVIEW

**Comment by mrpibb4201337** [comment]
f**k formatting prs all my homies hate formatting prs

**Comment by Hekzder** [comment]
### **First-time contributors need a maintainer to approve running workflows**

**Comment by mrpibb4201337** [comment]
🙏 🚬 🐇 🍅 🥇 🌭

**Comment by mrpibb4201337** [comment]
i'd love to commit right now but not on github; it's an older way of committing that a lot of people liked

**Pull request closed without merging**
