### PR TITLE
Crafting Rebalance

### PR DESCRIPTION
**Pull request by Hekzder**
## About The Pull Request

After lots of feedback about crafting and how tedious it is to do for a variety of reasons, this PR will rebalance a lot of aspects of crafting to hopefully make it more worthwhile. 

Item sizes for materials are reduced almost entirely across the board, however stack sizes are also reduced. In every circumstance, item size to stack size ratio has either stayed the same or improved, which should make it easier to actually haul around crafting materials. 

Crafting recipes are adjusted and new ones will be added. The files for recipes and materials have also been massively improved. Recipes have been split up into many different files and the materials file has been split in half, with metal materials getting their own file. 

There will also be some adjustments to loot spawners and the addition of some new ones, like a refined metal spawner we can use for mine or factory locations. 

## Why It's Good For The Game

Adjusting based on feedback is.... BASED!

### CODE REVIEW

**Comment by Hekzder** [comment]
This PR should be good to go.

**Comment by ProfessorPopoff** [comment]
mmmmerrmmm.. okay.

**Comment by Technobug14** [comment]
WOOOOOO LET'S GOOO YEAH BABY

**Comment by ProfessorPopoff** [comment]
https://user-images.githubusercontent.com/51188571/182268303-79d8604f-a0e3-4e27-a118-9b00ca6c471b.mp4

**Pull request merged**
